### ISSUE TITLE
[Request: Update to 1.16.1] AnvilFix-1.1.2.jar crashes on 1.16.1

### ISSUE THREAD

**Issue by calloatti** [NerdHubMC/AnvilFix#13] opened 2020-06-30 12:52 UTC
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### What happens:

https://paste.ee/p/skkfX

#### What you expected to happen:

Not crash

#### Steps to reproduce:

1. Start MC 1.16.1 with the mod in the mods folder
2. 
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- Anvil Fix: AnvilFix-1.1.2.jar
- Minecraft: 1.16.1
- Fabric Loader: 0.8.8-202
- Fabric API (if present): fabric-api-0.14.0+build.371-1.16.jar

**Comment by UpcraftLP** [comment] 2020-06-30 14:25
duplicate of #11

**Closed as completed by UpcraftLP** 2020-06-30 14:25 UTC
Labels: duplicate, 1.16
